import type { CompositionParams } from '../types/music';

export interface Preset {
  name: string;
  description: string;
  category: 'listening_room' | 'classical' | 'production' | 'mood';
  params: Partial<CompositionParams>;
}

export const PRESETS: Preset[] = [
  // Listening Room — curated for intimate live performance venues
  {
    name: 'Ronnie Scott\'s Late Set',
    description: 'Smoky, swinging jazz — like the 2am set at Ronnie\'s in Soho',
    category: 'listening_room',
    params: {
      key: 'D#',
      scale: 'dorian',
      tempo: 128,
      style: 'jazz',
      dynamics: 'swell',
      harmonicComplexity: 8,
      melodicDensity: 6,
      rhythmicVariety: 7,
      expressiveness: 9,
      measures: 16,
    },
  },
  {
    name: 'Nublu Midnight',
    description: 'Neo-soul grooves for the Lower East Side — Erykah meets Robert Glasper',
    category: 'listening_room',
    params: {
      key: 'F#',
      scale: 'pentatonic_minor',
      tempo: 82,
      style: 'neo_soul',
      dynamics: 'swell',
      harmonicComplexity: 7,
      melodicDensity: 5,
      rhythmicVariety: 6,
      expressiveness: 8,
      measures: 16,
    },
  },
  {
    name: 'Village Vanguard',
    description: 'Post-bop intensity — Coltrane, Mingus, the whole tradition',
    category: 'listening_room',
    params: {
      key: 'B',
      scale: 'mixolydian',
      tempo: 160,
      style: 'jazz',
      dynamics: 'dramatic',
      harmonicComplexity: 9,
      melodicDensity: 8,
      rhythmicVariety: 8,
      expressiveness: 10,
      measures: 16,
    },
  },
  {
    name: 'Brilliant Corners',
    description: 'Sunday afternoon at a Dalston listening bar — warm vinyl energy',
    category: 'listening_room',
    params: {
      key: 'G',
      scale: 'major',
      tempo: 95,
      style: 'jazz',
      dynamics: 'crescendo',
      harmonicComplexity: 6,
      melodicDensity: 4,
      rhythmicVariety: 5,
      expressiveness: 7,
      measures: 12,
    },
  },

  // Classical
  {
    name: 'Debussy\'s Garden',
    description: 'Impressionist watercolors — floating whole tones and suspended chords',
    category: 'classical',
    params: {
      key: 'D#',
      scale: 'whole_tone',
      tempo: 72,
      style: 'impressionist',
      dynamics: 'swell',
      harmonicComplexity: 7,
      melodicDensity: 3,
      rhythmicVariety: 4,
      expressiveness: 8,
      measures: 16,
    },
  },
  {
    name: 'Rachmaninoff Storm',
    description: 'Full romantic intensity — sweeping melodies, dramatic dynamics',
    category: 'classical',
    params: {
      key: 'C#',
      scale: 'harmonic_minor',
      tempo: 108,
      style: 'romantic',
      dynamics: 'dramatic',
      harmonicComplexity: 8,
      melodicDensity: 7,
      rhythmicVariety: 6,
      expressiveness: 10,
      measures: 16,
    },
  },
  {
    name: 'Glass Etude',
    description: 'Hypnotic minimalist patterns — Philip Glass meets Brian Eno',
    category: 'classical',
    params: {
      key: 'A',
      scale: 'major',
      tempo: 140,
      style: 'minimalist',
      dynamics: 'flat',
      harmonicComplexity: 3,
      melodicDensity: 7,
      rhythmicVariety: 2,
      expressiveness: 4,
      measures: 32,
    },
  },
  {
    name: 'Bach Chorale',
    description: 'Contrapuntal elegance — four-voice harmony in the Leipzig tradition',
    category: 'classical',
    params: {
      key: 'G',
      scale: 'major',
      tempo: 84,
      style: 'classical',
      dynamics: 'terraced',
      harmonicComplexity: 6,
      melodicDensity: 5,
      rhythmicVariety: 3,
      expressiveness: 5,
      measures: 8,
    },
  },

  // Production
  {
    name: 'Film Score Dawn',
    description: 'Cinematic tension and release — the sunrise over the opening credits',
    category: 'production',
    params: {
      key: 'D',
      scale: 'lydian',
      tempo: 76,
      style: 'cinematic',
      dynamics: 'crescendo',
      harmonicComplexity: 7,
      melodicDensity: 4,
      rhythmicVariety: 4,
      expressiveness: 8,
      measures: 24,
    },
  },
  {
    name: 'Synth Wave',
    description: 'Pulsing electronic arpeggios — Kraftwerk meets Aphex Twin',
    category: 'production',
    params: {
      key: 'A',
      scale: 'natural_minor',
      tempo: 126,
      style: 'electronic',
      dynamics: 'terraced',
      harmonicComplexity: 5,
      melodicDensity: 8,
      rhythmicVariety: 6,
      expressiveness: 5,
      measures: 16,
    },
  },
  {
    name: 'Ambient Drift',
    description: 'Weightless texture — Brian Eno\'s Music for Airports reborn',
    category: 'production',
    params: {
      key: 'E',
      scale: 'pentatonic_major',
      tempo: 60,
      style: 'ambient',
      dynamics: 'swell',
      harmonicComplexity: 4,
      melodicDensity: 2,
      rhythmicVariety: 2,
      expressiveness: 6,
      measures: 32,
    },
  },

  // Mood
  {
    name: 'Rainy Afternoon',
    description: 'Contemplative minor-key beauty — perfect for a grey London day',
    category: 'mood',
    params: {
      key: 'E',
      scale: 'natural_minor',
      tempo: 88,
      style: 'romantic',
      dynamics: 'decrescendo',
      harmonicComplexity: 5,
      melodicDensity: 4,
      rhythmicVariety: 3,
      expressiveness: 7,
      measures: 16,
    },
  },
  {
    name: 'Golden Hour',
    description: 'Warm, optimistic Lydian glow — like the magic hour before sunset',
    category: 'mood',
    params: {
      key: 'F',
      scale: 'lydian',
      tempo: 100,
      style: 'impressionist',
      dynamics: 'swell',
      harmonicComplexity: 6,
      melodicDensity: 5,
      rhythmicVariety: 4,
      expressiveness: 7,
      measures: 12,
    },
  },
  {
    name: 'Night Blues',
    description: 'Down-tempo blues for solitary reflection',
    category: 'mood',
    params: {
      key: 'A',
      scale: 'blues',
      tempo: 70,
      style: 'jazz',
      dynamics: 'decrescendo',
      harmonicComplexity: 5,
      melodicDensity: 4,
      rhythmicVariety: 5,
      expressiveness: 8,
      measures: 12,
    },
  },
];
