import type { ListeningRoomPreset } from '../types/music';

export const LISTENING_ROOM_PRESETS: ListeningRoomPreset[] = [
  {
    name: 'Blue Note After Hours',
    description: 'Smoky late-set jazz — Bill Evans meets Herbie. Sophisticated harmony, gentle swing, intimate dynamics.',
    params: {
      key: 'D#',
      scale: 'dorian',
      tempo: 92,
      style: 'jazz',
      dynamics: 'swell',
      harmonicComplexity: 8,
      melodicDensity: 6,
      rhythmicVariety: 7,
      expressiveness: 8,
      measures: 16,
    },
    category: 'jazz_club',
  },
  {
    name: 'Ronnie Scott\'s Midnight',
    description: 'Post-bop intensity — angular lines, complex changes, rhythmic fire. For the cats who stay past 1 AM.',
    params: {
      key: 'F',
      scale: 'melodic_minor',
      tempo: 138,
      style: 'post_bop',
      dynamics: 'dramatic',
      harmonicComplexity: 9,
      melodicDensity: 8,
      rhythmicVariety: 9,
      expressiveness: 9,
      measures: 16,
    },
    category: 'jazz_club',
  },
  {
    name: 'Debussy Salon',
    description: 'Impressionist colour — whole-tone shimmer, modal ambiguity, watercolour dynamics. Sunday afternoon at the Musée.',
    params: {
      key: 'G#',
      scale: 'whole_tone',
      tempo: 72,
      style: 'impressionist',
      dynamics: 'swell',
      harmonicComplexity: 7,
      melodicDensity: 4,
      rhythmicVariety: 4,
      expressiveness: 8,
      measures: 12,
    },
    category: 'salon',
  },
  {
    name: 'Chopin Nocturne',
    description: 'Late Romantic introspection — singing melody over arpeggiated accompaniment, rubato-rich, deeply personal.',
    params: {
      key: 'D#',
      scale: 'natural_minor',
      tempo: 66,
      style: 'late_romantic',
      dynamics: 'swell',
      harmonicComplexity: 7,
      melodicDensity: 5,
      rhythmicVariety: 4,
      expressiveness: 10,
      measures: 16,
    },
    category: 'concert_hall',
  },
  {
    name: 'Village Vanguard',
    description: 'Classic trio format — walking bass, ride cymbal, lyrical melody. The sound of Greenwich Village.',
    params: {
      key: 'F',
      scale: 'dorian',
      tempo: 120,
      style: 'jazz',
      dynamics: 'terraced',
      harmonicComplexity: 7,
      melodicDensity: 6,
      rhythmicVariety: 7,
      expressiveness: 7,
      measures: 12,
    },
    category: 'jazz_club',
  },
  {
    name: 'D\'Angelo Bedroom',
    description: 'Neo-soul pocket — lush extended chords, behind-the-beat groove, warm and sensual.',
    params: {
      key: 'A#',
      scale: 'dorian',
      tempo: 84,
      style: 'neo_soul',
      dynamics: 'swell',
      harmonicComplexity: 8,
      melodicDensity: 5,
      rhythmicVariety: 6,
      expressiveness: 8,
      measures: 8,
    },
    category: 'late_night',
  },
  {
    name: 'Nils Frahm Studio',
    description: 'Minimalist piano with felt — sparse, deliberate, meditative. Every note matters.',
    params: {
      key: 'A',
      scale: 'major',
      tempo: 68,
      style: 'minimalist',
      dynamics: 'flat',
      harmonicComplexity: 3,
      melodicDensity: 3,
      rhythmicVariety: 2,
      expressiveness: 7,
      measures: 16,
    },
    category: 'studio',
  },
  {
    name: 'Copacabana Sunset',
    description: 'Bossa nova breeze — Jobim-inspired changes, nylon guitar, gentle samba. Rio at golden hour.',
    params: {
      key: 'F',
      scale: 'major',
      tempo: 126,
      style: 'bossa_nova',
      dynamics: 'flat',
      harmonicComplexity: 7,
      melodicDensity: 5,
      rhythmicVariety: 5,
      expressiveness: 6,
      measures: 12,
    },
    category: 'late_night',
  },
  {
    name: 'Film Noir Detective',
    description: 'Dark mystery — minor jazz, muted trumpet, smoky ambiguity. Chinatown meets Taxi Driver.',
    params: {
      key: 'D',
      scale: 'harmonic_minor',
      tempo: 96,
      style: 'film_noir',
      dynamics: 'dramatic',
      harmonicComplexity: 8,
      melodicDensity: 5,
      rhythmicVariety: 5,
      expressiveness: 8,
      measures: 12,
    },
    category: 'late_night',
  },
  {
    name: 'Wigmore Hall',
    description: 'Chamber music intimacy — string quartet texture, classical form, pure counterpoint.',
    params: {
      key: 'G',
      scale: 'major',
      tempo: 108,
      style: 'chamber',
      dynamics: 'crescendo',
      harmonicComplexity: 6,
      melodicDensity: 5,
      rhythmicVariety: 5,
      expressiveness: 7,
      measures: 16,
    },
    category: 'concert_hall',
  },
  {
    name: 'Lo-Fi Study Session',
    description: 'Tape-warm beats, jazzy Rhodes chords, vinyl crackle vibe. Infinite focus.',
    params: {
      key: 'D',
      scale: 'dorian',
      tempo: 78,
      style: 'lo_fi',
      dynamics: 'flat',
      harmonicComplexity: 6,
      melodicDensity: 4,
      rhythmicVariety: 5,
      expressiveness: 5,
      measures: 8,
    },
    category: 'studio',
  },
  {
    name: 'Hans Zimmer Sunrise',
    description: 'Cinematic grandeur — building from whisper to roar. Orchestral power with modern production.',
    params: {
      key: 'D',
      scale: 'natural_minor',
      tempo: 80,
      style: 'cinematic',
      dynamics: 'crescendo',
      harmonicComplexity: 6,
      melodicDensity: 4,
      rhythmicVariety: 5,
      expressiveness: 9,
      measures: 16,
    },
    category: 'concert_hall',
  },
  {
    name: 'Gospel Sunday',
    description: 'Church fire — big chords, call-and-response energy, Hammond organ warmth.',
    params: {
      key: 'A#',
      scale: 'major',
      tempo: 116,
      style: 'gospel',
      dynamics: 'crescendo',
      harmonicComplexity: 7,
      melodicDensity: 6,
      rhythmicVariety: 7,
      expressiveness: 9,
      measures: 12,
    },
    category: 'concert_hall',
  },
  {
    name: 'Brian Eno 4AM',
    description: 'Ambient generative — long tones, slow evolution, infinite space. Music for airports and insomnia.',
    params: {
      key: 'C',
      scale: 'lydian',
      tempo: 55,
      style: 'ambient',
      dynamics: 'flat',
      harmonicComplexity: 4,
      melodicDensity: 2,
      rhythmicVariety: 2,
      expressiveness: 6,
      measures: 24,
    },
    category: 'late_night',
  },
];
