import type { CompositionPreset, CompositionParams } from '../types/music';

export const COMPOSITION_PRESETS: CompositionPreset[] = [
  {
    name: 'Midnight in Manhattan',
    description: 'Intimate late-night jazz. Warm Rhodes, walking bass, brushes on drums.',
    params: {
      key: 'D#',
      scale: 'dorian',
      tempo: 78,
      timeSignature: [4, 4],
      measures: 8,
      style: 'late_night',
      dynamics: 'swell',
      harmonicComplexity: 8,
      melodicDensity: 5,
      rhythmicVariety: 6,
      expressiveness: 8,
    },
  },
  {
    name: 'Debussy Afternoon',
    description: 'Impressionist colours — whole-tone fragments, shimmering pads, no gravity.',
    params: {
      key: 'G#',
      scale: 'whole_tone',
      tempo: 66,
      timeSignature: [3, 4],
      measures: 8,
      style: 'impressionist',
      dynamics: 'swell',
      harmonicComplexity: 7,
      melodicDensity: 4,
      rhythmicVariety: 3,
      expressiveness: 9,
    },
  },
  {
    name: 'Neo Soul Brunch',
    description: 'Sunday morning grooves. Fretless bass, warm Rhodes, gentle swing.',
    params: {
      key: 'F',
      scale: 'dorian',
      tempo: 82,
      timeSignature: [4, 4],
      measures: 8,
      style: 'neo_soul',
      dynamics: 'swell',
      harmonicComplexity: 7,
      melodicDensity: 5,
      rhythmicVariety: 6,
      expressiveness: 7,
    },
  },
  {
    name: 'Lagos Sunrise',
    description: 'Afrobeat energy — driving polyrhythms, organ grooves, relentless drums.',
    params: {
      key: 'A',
      scale: 'mixolydian',
      tempo: 120,
      timeSignature: [4, 4],
      measures: 8,
      style: 'afrobeat',
      dynamics: 'flat',
      harmonicComplexity: 4,
      melodicDensity: 6,
      rhythmicVariety: 8,
      expressiveness: 6,
    },
  },
  {
    name: 'R&B After Dark',
    description: 'Contemporary R&B — analog pads, kalimba textures, pocket drums.',
    params: {
      key: 'C#',
      scale: 'natural_minor',
      tempo: 75,
      timeSignature: [4, 4],
      measures: 8,
      style: 'contemporary_rnb',
      dynamics: 'swell',
      harmonicComplexity: 7,
      melodicDensity: 5,
      rhythmicVariety: 5,
      expressiveness: 8,
    },
  },
  {
    name: 'Rachmaninov Study',
    description: 'Grand Romantic piano. Sweeping arcs, rich voicings, dramatic dynamics.',
    params: {
      key: 'C#',
      scale: 'natural_minor',
      tempo: 72,
      timeSignature: [4, 4],
      measures: 8,
      style: 'romantic',
      dynamics: 'dramatic',
      harmonicComplexity: 9,
      melodicDensity: 7,
      rhythmicVariety: 5,
      expressiveness: 10,
    },
  },
  {
    name: 'Minimalist Pulse',
    description: 'Reich-inspired repetition. Phasing patterns, evolving slowly.',
    params: {
      key: 'D',
      scale: 'major',
      tempo: 140,
      timeSignature: [4, 4],
      measures: 12,
      style: 'minimalist',
      dynamics: 'crescendo',
      harmonicComplexity: 3,
      melodicDensity: 8,
      rhythmicVariety: 3,
      expressiveness: 4,
    },
  },
  {
    name: 'Ipanema Evening',
    description: 'Bossa nova. Nylon guitar, gentle swing, upright bass walking the changes.',
    params: {
      key: 'F',
      scale: 'major',
      tempo: 130,
      timeSignature: [4, 4],
      measures: 8,
      style: 'bossa_nova',
      dynamics: 'flat',
      harmonicComplexity: 6,
      melodicDensity: 5,
      rhythmicVariety: 5,
      expressiveness: 6,
    },
  },
  {
    name: 'Lo-fi Study Session',
    description: 'Tape-warped keys, dusty drums, chill vibes. Background music for focus.',
    params: {
      key: 'A#',
      scale: 'pentatonic_minor',
      tempo: 72,
      timeSignature: [4, 4],
      measures: 8,
      style: 'lo_fi',
      dynamics: 'flat',
      harmonicComplexity: 5,
      melodicDensity: 4,
      rhythmicVariety: 4,
      expressiveness: 5,
    },
  },
  {
    name: 'Cinematic Trailer',
    description: 'Epic strings, driving percussion, massive climax. Film score energy.',
    params: {
      key: 'D',
      scale: 'natural_minor',
      tempo: 90,
      timeSignature: [4, 4],
      measures: 12,
      style: 'cinematic',
      dynamics: 'dramatic',
      harmonicComplexity: 6,
      melodicDensity: 5,
      rhythmicVariety: 6,
      expressiveness: 9,
    },
  },
  {
    name: 'Gospel Sunday',
    description: 'Hammond organ, joyful piano, uplifting progressions.',
    params: {
      key: 'C',
      scale: 'major',
      tempo: 96,
      timeSignature: [4, 4],
      measures: 8,
      style: 'gospel',
      dynamics: 'crescendo',
      harmonicComplexity: 7,
      melodicDensity: 6,
      rhythmicVariety: 6,
      expressiveness: 8,
    },
  },
  {
    name: 'Waltz in Vienna',
    description: 'Classical waltz. Elegant 3/4, piano melody, string accompaniment.',
    params: {
      key: 'A',
      scale: 'major',
      tempo: 140,
      timeSignature: [3, 4],
      measures: 8,
      style: 'classical',
      dynamics: 'swell',
      harmonicComplexity: 5,
      melodicDensity: 5,
      rhythmicVariety: 4,
      expressiveness: 7,
    },
  },
];

export function getPresetByName(name: string): CompositionPreset | undefined {
  return COMPOSITION_PRESETS.find(p => p.name === name);
}

export function applyPreset(preset: CompositionPreset, current: CompositionParams): CompositionParams {
  return { ...current, ...preset.params };
}
